### ISSUE TITLE
Which python version is needed

### ISSUE THREAD

**Issue by nitinmukesh** [neeek2303/EMOPortraits#11]
I am trying to install on Windows with python 3.9.

Please confirm which python version is needed to run this tool. Getting a lot of conflict in package version.

```
ERROR: Ignored the following versions that require a different python version: 11.0.0 Requires-Python >=3.11,<4.0
ERROR: Could not find a version that satisfies the requirement mediapipe==0.8.9.1 (from versions: 0.9.1.0, 0.9.2.1, 0.9.3.0, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.5, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.10.11, 0.10.13, 0.10.14)
ERROR: No matching distribution found for mediapipe==0.8.9.1
```

**Comment by nitinmukesh** [comment]
Never faced so many issues with the installation. So many dependency version conflicts.
No point in wasting so much time.

**Comment by jarvisyyk** [comment]
i cannot agree more.
so LivePotraits can be run completely without any bugs?

**Comment by johndpope** [comment]
make sure you got these weights here - i had to manually download them - otherwise they are 2kb webpages https://github.com/johndpope/nemo/blob/main/bootstrap.sh#L34
